server:
  port: 19977


mybatis-plus:
  type-aliases-package: com.quark.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/quark?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: asdqwe123
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 20
        max-wait: 1000
    timeout: 0