server:
  port: 1997

spring:
  datasource:
    dynamic:
      p6spy: true
      hikari:
        connection-timeout: 3000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: QuarkHikariCP
      primary: primary
      datasource:
        primary:
          username: root
          password: asdqwe123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/quark?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: UTF-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: localhost
    port: 6379